---
application:
  name: "yapb-api"
  project: "yapb"
  organization: "QoveryCommunity"
  dockerfile: Dockerfile
  publicly_accessible: true
  port: 3000
routers:
  - name: "main-yapb-api"
    routes:
      - application_name: "yapb-api"
        paths:
          - "/*"
